# Genetic constants
GENERATIONS = 2000
NUMBER_OF_CROMOSSOMES = 15
MUTATION = 0.15
DESIRED_FITNESS = 100


# Break Scheduling
COFFEE_1_START =    12
COFFEE_1_END =      14
LUNCH_START =       21
LUNCH_END =         29
COFFEE_2_START =    48
COFFEE_2_END =      50

# Conference limitations
NUMBER_OF_ROOMS =   4
BLOCK_TIME = 10
MAX_START_BLOCK =   57

MORNING_SESSION_START = 0
MORNING_SESSION_END = 11
AFTERNOON_SESSION_START = 30
AFTERNOON_SESSION_END = 41

INVALID_MORNING = [x for x in range(COFFEE_1_START,COFFEE_1_END + 1)]
INVALID_LUNCH = [x for x in range(LUNCH_START, LUNCH_END + 1)]
INVALID_AFTERNOON = [x for x in range(COFFEE_2_START, COFFEE_2_END + 1)]

INVALID_BLOCKS = set(INVALID_MORNING + INVALID_LUNCH + INVALID_AFTERNOON)

# Fitness parameters
FIT_SCHEDULE_COLLISIONS =  True
FIT_BREAK_COLLISIONS = True
FIT_SPEAKER_OCC =   True
FIT_SESSIONS_THEME =  True

WEIGHT_SPEAKER_COLL = 0.25
WEIGHT_SCHEDULE_COLL = 0.25
WEIGHT_BREAK_COLL = 0.25
WEIGHT_SESSION_THEME = 0.25

# Spreadsheet parameters
SHEET_COL_START =   3
SHEET_ROW_START =   4

TO_EXPORT = None
EXPORT_PATH = None